version: "3" #3으로 시작하는 최신 버전 사용

services:
  pytorch:
    build: .
    container_name: pytorch_jupyter #컨테이너명
    deploy: #--gpus all 옵션이랑 같음
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:5000"
    command: sleep infinity #docker compose 후 컨테이너 유지 방법1
    volumes:
      - ./workdir/:/root/workdir #윈도우경로/도커경로